exports.CREATE_TODO_TABLE = 'CREATE TABLE IF NOT EXISTS todos ( id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL,deadline TEXT,  desc TEXT ,completed TEXT DEFAULT "NO" NOT NULL)'
exports.CREATE_TODO_ENTRY = 'INSERT INTO todos(title,deadline,desc) VALUES(?,?,?)' 
exports.GET_ALL_TODO ='SELECT * FROM todos' 
exports.MARK_TODO_COMPLETED = 'UPDATE todos SET completed ="YES" where title= ?'
exports.DELETE_SELECTED_TODO = 'DELETE FROM todos WHERE title  = ? '